import { getServerSession } from 'next-auth';
import type { Metadata } from 'next';
// import localFont from 'next/font/local';
import './globals.css';
import { authOptions } from './api/auth/[...nextauth]/route';
import ClientSessionProvider from './clientSessionProvider';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default async function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	const session = await getServerSession(authOptions);
	return (
		<html lang='en'>
			<body className='h-screen'>
				<ClientSessionProvider session={session!}>
					{children}
				</ClientSessionProvider>
			</body>
		</html>
	);
}
